name: Build bottles.

on:
  pull_request:
    paths:
      - 'Formula/*'

jobs:
  build-bottles:
    if: startsWith(github.event.pull_request.title, 'Merge') == false
    runs-on: ubuntu-latest
    container:
      image: homebrew/brew
    steps:
      - name: Checkout tap
        uses: actions/checkout@v2
      - name: Setup tap
        run: |
          rm -rf $(brew --repository ${{github.repository}})
          mkdir -p $(brew --repository ${{github.repository}})
          ln -s $GITHUB_WORKSPACE $(brew --repository ${{github.repository}})
          ls -al $(brew --repository ${{github.repository}})
          brew tap
      - name: Build bottles
        run: |
          mkdir ~/bottles
          cd ~/bottles
          brew test-bot
      # - name: Copy bottles
      #   if: always()
      #   run: |
      #     cp -a ~/bottles $GITHUB_WORKSPACE
      # - name: Upload bottles
      #   if: always()
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: bottles
      #     path: bottles
